### PR TITLE
Windows and ARM, `v` support, linting, codebase refactor, CD, Cleaned deps, One folder for versions

### PR DESCRIPTION
**Pull request by JulesGuesnon**
Hey!

First of all thanks for this project, it's really cool, and we definitely need a version manager for Bun!

I initially wanted a version for Mac ARM, but after looking at the code and some behaviours, I made some improvements to have what I think is a better experience, and fixed all the current opened issues.

Although I think of most of the changes are a benefit for Bum, some of them might be too opinionated. Here is a full list of the changes:

Main changes:
- Adding ARM and Windows to targets
- Installing all the versions in `~/.bum/bun-versions/` rather than `./bun-versions`
- Supporting the `v` in front of version (`1.1.7 == v1.1.7`)

Internal changes:
- Removed `std-async` as it was also using `tokio`. Removed unused deps as well
- Converted all the `fs` and `io` code to `tokio` as it was using `std`
- Made a more explicit architecture
- Removed the `lib.rs` as the point is building an executable, but can put it back again
- Added linting
- Removed the dependences to Unix if the target is Windows

If it can be merged as is, It would be cool (would need to update again the URL in the `readme` and `install.sh`), but if you want some changes to be done, feel free to tell me and I'll update everything

### CODE REVIEW

**Comment by owenizedd** [comment]
Hi really appreciate the PR!
I don’t have the time to focus on this project for a while now, so this is really what I have been wanted to do.

I have some questions on the changes you mentioned changed the path, I have feeling this will impact existing users, what do you think?

Like they list of installed version after the new changes they cant see any version installed.

But probably it will be less invasive than I would expect, they will just install it again because the bum will think it’s a new version the local machine does not have.

Other thing with this means the executable is automatically generated am I correct?
I remember someone raise issue about they want to support some architecture, does this PR also do that?

**Comment by JulesGuesnon** [comment]
Thanks for the answer!

About the version, yes it would impact existing users, but as you said, they'll just have to install it again.
Also the point of this change is to share all the versions in one place as I don't see a lot of use cases where you want to share your versions locally (e.g: `./bun-versions`).
I may be missing something, but I'm pretty sure this is the way almost all the version managers are doing it.

About the executables, yes it'll automatically create them. And about the versioning, here's the process:
- Update the version in `Cargo.toml` and `install.sh` (the version in the `install.sh` could be removed if the version is not in the name of the executable. [Example](https://github.com/JulesGuesnon/bum/releases/tag/v0.6.1)) and push it
- Create a tag: `git tag -a vX.X.X` and write the changelog
- Push the tag `git push --tag` and the CD will automatically create the release

**Comment by owenizedd** [comment]
Fantastic, I will merge this PR, thanks!

**Comment by JulesGuesnon** [comment]
Oh ok thanks! 
Btw, before merging it I have to clean the `readme` and `install.sh`. Although we can probably let the windows part as basically I couldn't test anything

**Comment by owenizedd** [comment]
You're going to do it in this PR right?
Let me know when you did it.

**Comment by JulesGuesnon** [comment]
Hey @owenizedd ! 
I cleaned the references to my repo and I put back the `0.5.0` so you can release the `0.6.0` once it's merged

**Comment by owenizedd** [comment]
Thank you for the awesome improvement!

**Comment by Baltazore** [comment]
@owenizedd any plans for new release ?

**Comment by owenizedd** [comment]
I'm releasing it today, sorry for long delay :D

**Pull request merged**
